
    create table utenti (
        id integer generated by default as identity,
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        carrello integer[],
        primary key (id)
    );
