
    create table disegni (
        id integer not null,
        supporto varchar(255),
        tecnica varchar(255),
        primary key (id)
    );

    create table illustrazioni (
        data_illustrazione date not null,
        id integer generated by default as identity,
        oggetto_id integer unique,
        stile varchar(100),
        url_illustrazione varchar(5000) unique,
        primary key (id)
    );

    create table oggetti (
        data_creazione date,
        id integer generated by default as identity,
        autore varchar(255),
        descrizione varchar(255),
        dimensione varchar(255),
        immagine varchar(255),
        is_ai varchar(255),
        prezzo varchar(255),
        titolo varchar(255),
        primary key (id)
    );

    create table utenti (
        id integer generated by default as identity,
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        carrello integer[],
        primary key (id)
    );

    alter table if exists disegni 
       add constraint FK6alg6v09ceooiqxm5sbf64jpg 
       foreign key (id) 
       references oggetti;

    alter table if exists illustrazioni 
       add constraint FKkwmktow89vxupk4xghal0uson 
       foreign key (oggetto_id) 
       references oggetti;
